#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-deployed-app-remote-repository-hook() {
  declare desc="outputs the associated registry repository to stdout"
  declare APP="$1"
  verify_app_name "$APP"

  if [[ "$(fn-registry-enabled "$APP")" == "false" ]]; then
    return 0
  fi

  fn-registry-remote-repository "$APP"
}

registry-deployed-app-remote-repository-hook "$@"
