#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-deployed-app-image-repo-hook() {
  declare desc="outputs the current image repo username prefixed to /APP to stdout"
  declare APP="$1"

  if [[ "$(fn-registry-enabled "$APP")" == "false" ]]; then
    return 0
  fi

  fn-registry-deployed-image-repo "$APP"
}

registry-deployed-app-image-repo-hook "$@"
