#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

registry-deployed-app-image-tag-hook() {
  declare desc="outputs the current image tag version to stdout"
  declare APP="$1"

  if [[ "$(fn-registry-enabled "$APP")" == "false" ]]; then
    return 0
  fi

  fn-registry-tag-latest-local "$APP"
}

registry-deployed-app-image-tag-hook "$@"
