#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-post-delete() {
  declare APP="$1"
  fn-registry-config-destroy "$APP"
}

registry-post-delete "$@"
