#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"

registry-post-release-hook() {
  declare desc="pushes an app after a release to the docker registry"
  declare APP="$1"
  verify_app_name "$APP"

  if [[ "$(fn-registry-enabled "$APP")" == "false" ]]; then
    return 0
  fi

  dokku_log_info1 "Pushing image to registry"
  fn-registry-tag-increment "$APP"
  fn-registry-push "$APP" "$(fn-registry-tag-latest-local "$APP")"
}

registry-post-release-hook "$@"
