#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

registry-post-delete() {
  declare APP="$1"
  fn-plugin-property-destroy "registry" "$APP"
}

registry-post-delete "$@"
