#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

registry-uninstall() {
  declare PLUGIN="$1"
  if [[ "$PLUGIN" != "$PLUGIN_COMMAND_PREFIX" ]]; then
    return
  fi

  fn-plugin-property-destroy "registry" "_all_"
}

registry-uninstall "$@"
