#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-uninstall() {
  declare PLUGIN="$1"
  if [[ "$PLUGIN" != "$PLUGIN_COMMAND_PREFIX" ]]; then
    return
  fi

  fn-registry-config-destroy "_all_"
}

registry-uninstall "$@"
