#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-main-cmd() {
  declare desc="shows the registry status of an app"
  declare APP="$2"
  local cmd="$1"
  local APPS=$(dokku_apps)
  if [[ -n "$APP" ]]; then
    local APPS="$APP"
  fi

  dokku_col_log_info1_quiet "App Name" "Registry Status"
  local app
  for app in $APPS; do
    verify_app_name "$app"
    dokku_col_log_msg "$app" "$(fn-registry-enabled "$app")"
  done
}

registry-main-cmd "$@"
