#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-login-cmd() {
  declare desc="logs into a docker registry"
  declare REGISTRY_SERVER="$2" REGISTRY_USERNAME="$3" REGISTRY_PASSWORD="$4"
  local cmd="$1"

  if [[ -z "$REGISTRY_SERVER" ]]; then
    dokku_log_fail "Missing server argument"
  fi

  if [[ -z "$REGISTRY_USERNAME" ]]; then
    dokku_log_fail "Missing username argument"
  fi

  if [[ -z "$REGISTRY_PASSWORD" ]]; then
    dokku_log_fail "Missing password argument"
  fi

  dokku_log_info1 "Logging into ${REGISTRY_SERVER}"
  docker login --username "$REGISTRY_USERNAME" --password "$REGISTRY_PASSWORD" "$REGISTRY_SERVER" | sed "s/^/       /"
}

registry-login-cmd "$@"

