#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-pull-cmd() {
  declare desc="pulls a tag from a docker registry"
  declare APP="$2" TAG="$3"
  local cmd="$1"

  dokku_log_info1 "Pulling image from registry"
  fn-registry-pull "$APP" "$TAG"
}

registry-pull-cmd "$@"
