#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-push-cmd() {
  declare desc="pushes a tag from a docker registry"
  declare APP="$2" TAG="$3"
  local cmd="$1"

  dokku_log_info1 "Pushing image to registry"
  fn-registry-push "$APP" "$TAG"
}

registry-push-cmd "$@"
