#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

fn-in-array() {
  declare desc="return true if value ($1) is in list (all other arguments)"

  local e
  for e in "${@:2}"; do
    [[ "$e" == "$1" ]] && return 0
  done
  return 1
}

registry-set-cmd() {
  declare desc="sets a registry configuration value for an app"
  local cmd="$PLUGIN_COMMAND_PREFIX:set" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" KEY="$2" VALUE="$3"
  local VALID_KEYS=("image" "server" "username")
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -z "$KEY" ]] && dokku_log_fail "No key specified"

  if ! fn-in-array "$KEY" "${VALID_KEYS[@]}"; then
    dokku_log_fail "Invalid key specified, valid keys include: image, server, username"
  fi

  if [[ -z "$VALUE" ]]; then
    if [[ "$key" == "server" ]]; then
      VALUE="${VALUE%/}/"
    fi

    dokku_log_info2_quiet "Setting ${KEY} to ${VALUE}"
    fn-registry-config-write "$APP" "$KEY" "$VALUE"
  else
    dokku_log_info2_quiet "Unsetting ${KEY}"
    fn-registry-config-delete "$APP" "$KEY"
  fi
}

registry-set-cmd "$@"
