#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-set-username-cmd() {
  declare desc="sets the username for an app"
  declare APP="$2" DOKKU_REGISTRY_USERNAME="$3"
  local cmd="$1"
  verify_app_name "$APP"

  if [[ -z "$DOKKU_REGISTRY_USERNAME" ]]; then
    dokku_log_fail "No registry username specified"
  fi

  dokku_log_info1 "Setting username to $DOKKU_REGISTRY_USERNAME"
  fn-registry-config-write "$APP" DOKKU_REGISTRY_USERNAME "$DOKKU_REGISTRY_USERNAME"
}

registry-set-username-cmd "$@"
