#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-set-registry-cmd() {
  declare desc="sets the registry for an app"
  declare APP="$2" DOKKU_REGISTRY_SERVER="$3"
  local cmd="$1"
  verify_app_name "$APP"

  if [[ -z "$DOKKU_REGISTRY_SERVER" ]]; then
    dokku_log_fail "No remote registry specified"
  fi

  DOKKU_REGISTRY_SERVER="${DOKKU_REGISTRY_SERVER%/}/"
  dokku_log_info1 "Setting registry to $DOKKU_REGISTRY_SERVER"
  fn-registry-config-write "$APP" DOKKU_REGISTRY_SERVER "$DOKKU_REGISTRY_SERVER"
}

registry-set-registry-cmd "$@"
