#!/usr/bin/env bash
source "$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")" )" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/internal-functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

registry-tag-latest-local-cmd() {
  declare desc="shows latest local tag version"
  declare APP="$2"
  local cmd="$1"
  verify_app_name "$APP"

  fn-registry-tag-latest-local "$APP"
}

registry-tag-latest-local-cmd "$@"
