#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-tag-latest-local-cmd() {
  declare desc="shows latest local tag version"
  declare APP="$2"
  local cmd="$1"
  verify_app_name "$APP"

  fn-registry-tag-latest-local "$APP"
}

registry-tag-latest-local-cmd "$@"
