#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/registry/functions"

registry-unset-registry-cmd() {
  declare desc="unsets the registry for an app"
  declare APP="$2"
  local cmd="$1"
  verify_app_name "$APP"

  dokku_log_info1 "Unsetting registry"
  fn-registry-config-delete "$APP" DOKKU_REGISTRY_SERVER
}

registry-unset-registry-cmd "$@"
